### ISSUE TITLE
[DESIGN] Ship Permissions and Interaction

### ISSUE THREAD

**Issue by JensenJ** [JensenJ/SpaceSurvival#4]
**Is your feature request related to a problem? Please describe.**
Ships feel very bland and only can be interacted with by the player who owns them. There should be a system where players can interact with other ships. This could include driving permissions, or even criminal actions such as stealing. Also, ships currently can only have 1 player in them at a time, this is not realistic for larger ships such as cargo haulers as a ship may need a larger crew to run.

**Describe the solution you'd like**
Player's should have a way of controlling permissions and systems that other players can have over their ship. For example, should other players be able to drive the ship? Multiple player should be able to get in a ship and their should be a seat system, also controls such as firing weapons / driving could be delegated to other players.

**Describe alternatives you've considered**
Permissions could be determined upon based on the player's faction. For example, a more closed faction may not allow any other factions to interact with the ship.
Players could have a friends or "trusted" list of other players who they allow certain permissions.

**Additional context**
The system should work regardless of the number of players and should work independently of any other systems.

**Comment by JakeAllswo** [comment]
I've started on the document, New section header called 'Ship Interactions'. So far it describes the roles that people can do under the command of their captain/owner.
